// <auto-generated />
using AutoRpaTool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRpaTool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323083650_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AutoRpaTool.Models.ActionNode", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("ClickOffsetX")
                        .HasColumnType("double");

                    b.Property<double>("ClickOffsetY")
                        .HasColumnType("double");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("InputValue")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsStartNode")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("LocationX")
                        .HasColumnType("double");

                    b.Property<double>("LocationY")
                        .HasColumnType("double");

                    b.Property<double>("MatchThreshold")
                        .HasColumnType("double");

                    b.Property<string>("NextNodeOnFail")
                        .HasColumnType("longtext");

                    b.Property<string>("NextNodeOnSuccess")
                        .HasColumnType("longtext");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("TargetImagePath")
                        .HasColumnType("longtext");

                    b.Property<int>("WaitMs")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ActionNodes");
                });

            modelBuilder.Entity("AutoRpaTool.Models.BranchRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NextNodeId")
                        .HasColumnType("longtext");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TargetImagePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("BranchRules");
                });

            modelBuilder.Entity("AutoRpaTool.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TriggerWindowTitle")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("AutoRpaTool.Models.ActionNode", b =>
                {
                    b.HasOne("AutoRpaTool.Models.Scenario", "Scenario")
                        .WithMany("Nodes")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("AutoRpaTool.Models.BranchRule", b =>
                {
                    b.HasOne("AutoRpaTool.Models.ActionNode", "Node")
                        .WithMany("BranchRules")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("AutoRpaTool.Models.ActionNode", b =>
                {
                    b.Navigation("BranchRules");
                });

            modelBuilder.Entity("AutoRpaTool.Models.Scenario", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
