// <auto-generated />
using AutoRpaTool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRpaTool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoRpaTool.Models.ActionNode", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InputValue")
                        .HasColumnType("longtext");

                    b.Property<double>("LocationX")
                        .HasColumnType("double");

                    b.Property<double>("LocationY")
                        .HasColumnType("double");

                    b.Property<string>("NextNodeOnFail")
                        .HasColumnType("longtext");

                    b.Property<string>("NextNodeOnSuccess")
                        .HasColumnType("longtext");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("TargetData")
                        .HasColumnType("longtext");

                    b.HasKey("NodeId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ActionNodes");
                });

            modelBuilder.Entity("AutoRpaTool.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("AutoRpaTool.Models.ActionNode", b =>
                {
                    b.HasOne("AutoRpaTool.Models.Scenario", "Scenario")
                        .WithMany("Nodes")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("AutoRpaTool.Models.Scenario", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
